CREATE TABLE User (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255)
);
CREATE TABLE Todo (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT now(),
  text TEXT,
  done BOOLEAN NOT NULL DEFAULT false,
  userId INTEGER NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(id)
);
